"""add_room_tables

Revision ID: 6a3955453f30
Revises: c5d2e8f1a4b7
Create Date: 2026-05-14 00:22:23.690066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a3955453f30'
down_revision: Union[str, Sequence[str], None] = 'c5d2e8f1a4b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('room_code', sa.String(length=6), nullable=False),
    sa.Column('host_user_id', sa.String(length=36), nullable=False),
    sa.Column('video_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('max_players', sa.Integer(), nullable=False),
    sa.Column('max_replays', sa.Integer(), nullable=False),
    sa.Column('exam_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('total_sentences', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['host_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_sessions_room_code'), 'room_sessions', ['room_code'], unique=True)
    op.create_table('room_answers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('room_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('sentence_index', sa.Integer(), nullable=False),
    sa.Column('user_input', sa.Text(), nullable=False),
    sa.Column('is_skipped', sa.Boolean(), nullable=False),
    sa.Column('accuracy_score', sa.Float(), nullable=False),
    sa.Column('time_bonus', sa.Float(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('replay_count', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['room_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'user_id', 'sentence_index', name='uq_room_answer')
    )
    op.create_index('idx_room_answers_room_sentence', 'room_answers', ['room_id', 'sentence_index'], unique=False)
    op.create_table('room_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('room_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('sentences_done', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('is_ready', sa.Boolean(), nullable=False),
    sa.Column('is_connected', sa.Boolean(), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['room_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'user_id', name='uq_room_member')
    )
    op.create_index('idx_room_members_room', 'room_members', ['room_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_room_members_room', table_name='room_members')
    op.drop_table('room_members')
    op.drop_index('idx_room_answers_room_sentence', table_name='room_answers')
    op.drop_table('room_answers')
    op.drop_index(op.f('ix_room_sessions_room_code'), table_name='room_sessions')
    op.drop_table('room_sessions')
    # ### end Alembic commands ###
