"""add_phonetic_audio_context_translation_and_word_cache

Revision ID: 6e4d1649c168
Revises: ae2f838a3789
Create Date: 2026-04-18 17:05:02.553375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e4d1649c168'
down_revision: Union[str, Sequence[str], None] = 'ae2f838a3789'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word_cache',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('word', sa.String(length=200), nullable=False),
    sa.Column('context_hash', sa.String(length=64), nullable=False),
    sa.Column('phonetic', sa.String(length=100), nullable=True),
    sa.Column('audio_url', sa.Text(), nullable=True),
    sa.Column('vietnamese_meaning', sa.Text(), nullable=True),
    sa.Column('context_translation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word', 'context_hash', name='uq_word_cache_word_context')
    )
    op.create_index(op.f('ix_word_cache_context_hash'), 'word_cache', ['context_hash'], unique=False)
    op.create_index(op.f('ix_word_cache_word'), 'word_cache', ['word'], unique=False)
    op.add_column('saved_words', sa.Column('phonetic', sa.String(length=100), nullable=True))
    op.add_column('saved_words', sa.Column('audio_url', sa.Text(), nullable=True))
    op.add_column('saved_words', sa.Column('context_translation', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saved_words', 'context_translation')
    op.drop_column('saved_words', 'audio_url')
    op.drop_column('saved_words', 'phonetic')
    op.drop_index(op.f('ix_word_cache_word'), table_name='word_cache')
    op.drop_index(op.f('ix_word_cache_context_hash'), table_name='word_cache')
    op.drop_table('word_cache')
    # ### end Alembic commands ###
