"""add part_of_speech to saved_words and word_cache

Revision ID: 8ec9c1c0784c
Revises: 4f5b8c1e9d2a
Create Date: 2026-04-28 00:01:20.636029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ec9c1c0784c'
down_revision: Union[str, Sequence[str], None] = '4f5b8c1e9d2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_words', sa.Column('part_of_speech', sa.String(length=30), nullable=True))
    op.add_column('word_cache', sa.Column('part_of_speech', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('word_cache', 'part_of_speech')
    op.drop_column('saved_words', 'part_of_speech')
    # ### end Alembic commands ###
