"""add part_of_speech to saved_words and word_cache

Revision ID: a6780b8f967c
Revises: 8ec9c1c0784c
Create Date: 2026-04-28 00:12:14.822663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6780b8f967c'
down_revision: Union[str, Sequence[str], None] = '8ec9c1c0784c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
