"""add unique constraint user_id+video_id on dictation_attempts

Revision ID: ae2f838a3789
Revises: 2707515a3b82
Create Date: 2026-04-04 22:00:34.524685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae2f838a3789'
down_revision: Union[str, Sequence[str], None] = '2707515a3b82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Step 1: Delete duplicate rows, keeping only the most recently updated attempt per (user_id, video_id)
    op.execute("""
        DELETE FROM dictation_attempts
        WHERE id NOT IN (
            SELECT DISTINCT ON (user_id, video_id) id
            FROM dictation_attempts
            ORDER BY user_id, video_id, updated_at DESC
        )
    """)
    # Step 2: Now safe to add the unique constraint
    op.create_unique_constraint('uq_attempts_user_video', 'dictation_attempts', ['user_id', 'video_id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_attempts_user_video', 'dictation_attempts', type_='unique')
    # ### end Alembic commands ###
